# Generated by Django 6.0.6 on 2026-07-04 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('numero_id', models.CharField(max_length=40, unique=True, verbose_name='matricule')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-président'), ('secretaire_general', 'Secrétaire général'), ('questeur', 'Questeur'), ('depute', 'Député'), ('administration', 'Administration'), ('citoyen', 'Citoyen')], default='depute', max_length=30)),
                ('fonction', models.CharField(blank=True, max_length=120)),
                ('sexe', models.CharField(blank=True, choices=[('F', 'Femme'), ('M', 'Homme')], max_length=1)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('groupe_parlementaire', models.CharField(blank=True, max_length=80)),
                ('photo_url', models.CharField(blank=True, max_length=300)),
                ('biographie', models.TextField(blank=True)),
                ('totp_secret', models.CharField(blank=True, max_length=64)),
                ('totp_active', models.BooleanField(default=False)),
                ('doit_changer_mdp', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ConnexionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('date_deconnexion', models.DateTimeField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_connexion'],
            },
        ),
    ]
