# Generated by Django 6.0.6 on 2026-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='circonscription',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='deputes/', verbose_name='photo'),
        ),
    ]
