# Generated by Django 6.0.6 on 2026-07-04 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=12)),
                ('cible_role', models.CharField(default='tous', max_length=30)),
                ('date_publication', models.DateTimeField()),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_ar', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_presidees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reference', models.CharField(max_length=40, unique=True)),
                ('titre', models.CharField(max_length=400)),
                ('resume', models.TextField(blank=True)),
                ('type_texte', models.CharField(choices=[('projet', 'Projet de loi'), ('proposition', 'Proposition de loi')], default='projet', max_length=12)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('prioritaire', 'Prioritaire'), ('urgence_nationale', 'Urgence nationale')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('depose', 'Déposé'), ('en_commission', 'En commission'), ('en_debat', 'En débat'), ('au_vote', 'Au vote'), ('adopte', 'Adopté'), ('promulgue', 'Promulgué'), ('rejete', 'Rejeté'), ('retire', 'Retiré')], default='depose', max_length=15)),
                ('depose_par', models.CharField(blank=True, max_length=200)),
                ('date_depot', models.DateTimeField()),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lois', to='parlement.commission')),
                ('rapporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lois_rapportees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('categorie', models.CharField(choices=[('loi_adoptee', 'Loi adoptée'), ('rapport', 'Rapport'), ('proces_verbal', 'Procès-verbal'), ('reglement', 'Règlement'), ('ordre_du_jour', 'Ordre du jour'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier_url', models.CharField(max_length=300)),
                ('taille_ko', models.IntegerField(blank=True, null=True)),
                ('acces', models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel')], default='public', max_length=15)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('loi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='parlement.loi')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='LoiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='parlement.loi')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoiEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('date_etape', models.DateTimeField()),
                ('loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='parlement.loi')),
            ],
            options={
                'ordering': ['date_etape'],
            },
        ),
        migrations.CreateModel(
            name='MessageCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('sujet', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée'), ('classee', 'Classée')], default='nouvelle', max_length=10)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='parlement.commission')),
                ('depute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='OperationFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(default='XAF', max_length=8)),
                ('motif', models.CharField(max_length=250)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='approuvee', max_length=12)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('piece_justificative_url', models.CharField(blank=True, max_length=300)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_approuvees', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=80)),
                ('objectif_signatures', models.IntegerField(default=1000)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Clôturée'), ('traitee', 'Traitée')], default='active', max_length=10)),
                ('date_creation', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petitions', to='parlement.commission')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('type_evenement', models.CharField(choices=[('seance_pleniere', 'Séance plénière'), ('commission', 'Commission'), ('reunion', 'Réunion'), ('ceremonie', 'Cérémonie'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('prevue', 'Prévue'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='prevue', max_length=12)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='parlement.commission')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('ouvert', models.BooleanField(default=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('loi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrutins', to='parlement.loi')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrutins', to='parlement.seance')),
            ],
            options={
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='CommissionMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_commission', models.CharField(choices=[('president', 'Président'), ('vice_president', 'Vice-président'), ('rapporteur', 'Rapporteur'), ('membre', 'Membre')], default='membre', max_length=20)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='parlement.commission')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('commission', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='PetitionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=120)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='parlement.petition')),
            ],
            options={
                'unique_together': {('petition', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('excuse', 'Excusé')], default='present', max_length=10)),
                ('depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='parlement.seance')),
            ],
            options={
                'unique_together': {('seance', 'depute')},
            },
        ),
        migrations.CreateModel(
            name='VoteBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('POUR', 'Pour'), ('CONTRE', 'Contre'), ('ABSTENTION', 'Abstention')], max_length=10)),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('hash_verif', models.CharField(blank=True, max_length=32)),
                ('depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='parlement.votesession')),
            ],
            options={
                'unique_together': {('session', 'depute')},
            },
        ),
    ]
