# Generated by Django 6.0.6 on 2026-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='fichier (PDF)'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='date_scrutin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votesession',
            name='nb_abstention',
            field=models.PositiveIntegerField(default=0, verbose_name='abstentions'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='nb_contre',
            field=models.PositiveIntegerField(default=0, verbose_name='voix contre'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='nb_pour',
            field=models.PositiveIntegerField(default=0, verbose_name='voix pour'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='statut_numerisation',
            field=models.CharField(choices=[('numerise', 'Numérisé'), ('en_cours', 'En cours de numérisation')], default='numerise', max_length=12),
        ),
        migrations.AddField(
            model_name='votesession',
            name='statut_resultat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('adopte', 'Adopté'), ('rejete', 'Rejeté')], default='en_attente', max_length=12),
        ),
        migrations.AddField(
            model_name='votesession',
            name='type_session',
            field=models.CharField(choices=[('ordinaire', 'Session ordinaire'), ('extraordinaire', 'Session extraordinaire')], default='ordinaire', max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
